# Built with Jekyll 3.2.0

# Setup
title:               Evan
tagline:             'Software / Writing'
description:         "This is the website of Evan Kozliner, software engineer and, sometimes, writer. I'm interested in technology and philosophy."
url:                 'http://minicomp.github.io'
baseurl:             '/ed'

# About/contact
author:
  name:              Evan Kozliner
  url:               https://twitter.com/evankozliner
  email:             evankozliner@gmail.com

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."
